// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi18h64sJXMDdl4OqZKq50Fx-vRsKXCl0',
    appId: '1:290626295960:web:113abad029776ee1d6d8ed',
    messagingSenderId: '290626295960',
    projectId: 'plant-app-629bc',
    authDomain: 'plant-app-629bc.firebaseapp.com',
    storageBucket: 'plant-app-629bc.appspot.com',
    measurementId: 'G-1F1204R3T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP9O8z6q3G9fyZuLg82ywiYfUmw5sbUJ4',
    appId: '1:290626295960:android:1ec0aab40759ace5d6d8ed',
    messagingSenderId: '290626295960',
    projectId: 'plant-app-629bc',
    storageBucket: 'plant-app-629bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo4EPKUu4UFb1G8aPq-0TtB1SEEXRo624',
    appId: '1:290626295960:ios:8375557fab7ba403d6d8ed',
    messagingSenderId: '290626295960',
    projectId: 'plant-app-629bc',
    storageBucket: 'plant-app-629bc.appspot.com',
    iosBundleId: 'com.example.plantApp',
  );
}
